version: '3'

services:
  access-node:
    build: ./access-node
    ports:
      - "8080:8080"
    depends_on:
      - "insite-nest-module"
    command: ["http://insite-nest-module:9000"]

  insite-nest-module:
    build: ./nest-module
    volumes:
      - ./scripts:/scripts/
    ports:
      - "9000-9005:9000-9005"
    environment:
      - SCRIPT_NAME=stim.py
